pygments: true
permalink: /post/:title
markdown: redcarpet
exclude: ['Gemfile','Gemfile.lock','Rakefile','.git']
paginate: 4
name: "Ardo's blog"
description: "Ardo messes around"
url: ardoi.github.io
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
